/*
program yang mengandung tipe data dalam c++
*/
#include <iostream.h>
#include <conio.h>
void main()
{
clrscr();
char huruf;
huruf = 'B';
cout<< "isi huruf bertipe char = "<<huruf<<'\n';
int angka;
angka = 123;
cout<<"isi bertipe int = "<<angka<<'\n';
long jumlah;
jumlah = 12345678;
cout<<"isi jumlah beripe long = "<<jumlah<<'\n';
float nilai;
nilai = 234.543;
cout<<"isi nilai bertipe float ="<<nilai<<'\n';
double cacah;
cacah = 3453.345;
cout<<"isi cacah bertipe double = "<<cacah<<'\n';
long double total;
total = 23456.3945;
cout<<"isi total bertipe long double = "<<total<<'\n';
getch();
}